### ISSUE TITLE
Space added in `$foo`

### ISSUE THREAD

**Issue by max-sixty** [shssoichiro/sqlformat-rs#18]
Often `$foo` is used for parameters in SQL; e.g. [sqllite](https://www.sqlite.org/lang_expr.html). 

That works in `sqlformat-rs` for numbers like `$1`. 

But for word characters, a space gets inserted:

```sql
SELECT
  *
FROM
  problem
WHERE
  file_hash = $ hash
```

**Comment by shssoichiro** [comment]
Thanks, when researching the implementation I look at what is supported across different platforms and saw that Postgres, which also uses `$` params, only accepts number args. Since sqlite accepts named args I'll add support for those.
