### ISSUE TITLE
`uppercase=false` does not lowercase the query

### ISSUE THREAD

**Issue by bbstilson** [shssoichiro/sqlformat-rs#21]
Piggy backing off : https://github.com/nrempel/sleek/issues/16

If `uppercase` is `false`, the query is not lowercased. Either there should be an explicit flag to lowercase the query, or `uppercase = false` should lowercase the query.

**Comment by wugeer** [comment]
@bbstilson Currently,  if `uppercase` is `false`, it means that no action will be taken on the query .  I have a note to fix this issue, and I'll submit a PR later

**Comment by wugeer** [comment]
@bbstilson Currently,  if `uppercase` is `false`, it means that no action will be taken on the query .  I have a note to fix this issue, and I'll submit a PR later
