### ISSUE TITLE
Posgresql: Incorrect intentation for one-byte character literal

### ISSUE THREAD

**Issue by andreoss** [shssoichiro/sqlformat-rs#25]
PostgreSQL provides a special syntax for a one-byte character `E'<char>`'
sqlformat puts space after `E` which is incorrect

```
$ echo "SELECT 'new line -> '||E'\n';" | sleek                                                                                                                              
SELECT                                                                                                                                                                       
    'new line -> ' || E '\n';
```

**Comment by wugeer** [comment]
@andreoss Hello, this issue has been fixed in the unreleased version. You can wait for the new version to be released, then update the sqlformat package to the latest version in sleek and try again.  :)

![image](https://github.com/user-attachments/assets/0570b6fe-7933-4d66-a17b-a28558917799)

**Comment by andreoss** [comment]
Thanks
