### ISSUE TITLE
Ignore keywords for `uppercase=True`

### ISSUE THREAD

**Issue by utkarshgupta137** [shssoichiro/sqlformat-rs#33]
We use ClickHouse & it doesn't like `STRING`, it prefers `String`. It would be nice if we there was an ignore keyword list for uppercase.

**Comment by wugeer** [comment]
@utkarshgupta137 That sounds good, I'll give it a try and work on it. :)

**Comment by wugeer** [comment]
@utkarshgupta137 Since this modification conflicts with this PR https://github.com/shssoichiro/sqlformat-rs/pull/50, I plan to wait for this PR to end before submitting a new PR to fix this problem.

**Comment by utkarshgupta137** [comment]
Waiting for a new release 👍🏻
