### ISSUE TITLE
Latest patch release seems to contain a breaking change

### ISSUE THREAD

**Issue by jplatte** [shssoichiro/sqlformat-rs#54]
[`sqlformat::format`](https://docs.rs/sqlformat/0.2.7/sqlformat/fn.format.html) now requires a `&FormatOptions<_>` for its third argument, when it used to take an owned `FormatOptions`. This makes SQLx fail to compile with that version.

Please consider yanking `v0.2.7`.

**Comment by abonander** [comment]
cc https://github.com/launchbadge/sqlx/issues/3544

**Comment by shssoichiro** [comment]
The version has been yanked. I'd like to avoid this in the future. Are there any suggestions for catching this early? I recall there being a cargo tool to semi-automate this, though I can't remember what it was called.

**Comment by jplatte** [comment]
You're probably thinking of https://github.com/obi1kenobi/cargo-semver-checks

**Comment by shssoichiro** [comment]
It looks like the breaking change is difficult to isolate and revert without reverting meaningful changes. As such, I'm moving forward releasing the new version as `0.3.0` instead so that it is properly acknowledged as breaking.
