### ISSUE TITLE
Relax regex constraint?

### ISSUE THREAD

**Issue by sunshowers** [shssoichiro/sqlformat-rs#55]
Hi, and thanks for maintaining sqlformat!

I noticed that there was a constraint on regex where it was forced to be equal to 1.6: https://github.com/shssoichiro/sqlformat-rs/blob/f2e955903d348482f854a5456846544817d1fc55/Cargo.toml#L19

Could this be relaxed to be 1.6 or above? That's the standard generally followed across the Rust ecosystem. We use other crates that require a more modern regex, which become incompatible with sqlformat.

Thanks!

**Comment by shssoichiro** [comment]
I wonder if this was locked in order to prevent the minimum rustc version from breaking. I'll take a look and provide an update soon.

**Comment by sunshowers** [comment]
Thanks. I think in general, if people are using an old MSRV the burden is on them to check in a Cargo.lock file with the older versions of dependencies.

**Comment by sunshowers** [comment]
Thank you so much!
