### ISSUE TITLE
Unexpected whitespace in casting types

### ISSUE THREAD

**Issue by pnezis** [shssoichiro/sqlformat-rs#61]
For the following input:

```sql
SELECT birth_date::date FROM users
```

the following output is produced:

```sql
SELECT
  birth_date :: date
FROM
  users
```

Notice the unexpected whitespace around the casting operator. Expected formatted query:

```sql
SELECT
  birth_date::date
FROM
  users
```

**Comment by dkuku** [comment]
do you know if it was working ok on previous version  (0.3.0)?

**Comment by pnezis** [comment]
> do you know if it was working ok on previous version (0.3.0)?

From a quick test it did not work ok.

Another example that may be more tricky to handle is if the casting is after a closing parenthesis:

```
SELECT (x - y)::integer FROM table;
```
